# MySQL.  Versions 4.1 and 5.0 are recommended.
#
#
# Be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: devise_test_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
  
#production:
#  adapter: mysql2
#  encoding: utf8
#  reconnect: false
#  database: mydb
#  pool: 5
#  username: root
#  password: 
#  socket: /var/run/mysqld/mysqld.sock

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: devise_test_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock